version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8081:8081"
    volumes:
      - ./web:/web
      - ./nginx:/etc/nginx/conf.d

  app:
      volumes:
        - .:/app
      ports:
        - "8080:8080"
      build:
        context: .
        dockerfile: app/Dockerfile
      command: gunicorn -b 0.0.0.0:8080 app.server:app

